<?php

return [
    [
        'name' => 'classname',
        'title' => '渲染文本框元素',
        'type' => 'string',
        'content' => [],
        'value' => '.editor',
        'rule' => 'required',
        'msg' => '',
        'tip' => '用于对指定的元素渲染，一般情况下无需修改',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'height',
        'title' => '默认高度',
        'type' => 'string',
        'content' => [],
        'value' => '250',
        'rule' => 'required',
        'msg' => '',
        'tip' => '编辑器默认高度，auto表示自适应高度',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'minHeight',
        'title' => '默认高度',
        'type' => 'number',
        'content' => [],
        'value' => '250',
        'rule' => 'required',
        'msg' => '',
        'tip' => '编辑器最低高度',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'toolbarFloat',
        'title' => '工具栏浮动',
        'type' => 'radio',
        'content' => [
            1 => '是',
            0 => '否',
        ],
        'value' => '0',
        'rule' => 'required',
        'msg' => '',
        'tip' => '是否浮动工具栏',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'toolbar',
        'title' => '默认工具栏',
        'type' => 'text',
        'content' => [],
        'value' => '["title", "bold", "italic", "underline", "strikethrough", "fontScale", "color", "|", "ol", "ul", "blockquote", "code", "table", "|", "link", "image", "hr", "|", "indent", "outdent", "alignment"]',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'mobileToolbar',
        'title' => '移动端工具栏',
        'type' => 'text',
        'content' => [],
        'value' => '["bold", "underline", "strikethrough", "color", "ul", "ol"]',
        'rule' => 'required',
        'msg' => '',
        'tip' => '移动端工具栏配置',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'placeholder',
        'title' => '默认占位文字',
        'type' => 'string',
        'content' => [],
        'value' => '',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => '__tips__',
        'title' => '温馨提示',
        'type' => 'string',
        'content' => [],
        'value' => '工具栏配置请参考文档：https://simditor.tower.im/docs/doc-config.html',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
];
